[package]
name = "osvitarium-backend"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }

axum = "0.8.3"
axum-extra = { version = "0.10.1", features = [ "typed-header" ] }
sea-orm = { version = "1.1.8", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "mock"] }
tokio = { version = "1.44.2", features = ["full"] }
serde = "1.0.219"
serde_json = "1.0.140"
clap = "4.5.36"
log = "0.4.27"
env_logger = "0.11.8"
argon2 = "0.5.3"
jsonwebtoken = "9.3.1"
mockall = "0.13.1"
tower = "0.5.2"

[dev-dependencies]
rstest = "0.25.0"
