[package]
name = "osvitarium-backend"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }

axum = "0.8.3"
sea-orm = { version = "1.1.8", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "mock"] }
tokio = { version = "1.44.2", features = ["full"] }
