//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "course")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub course_id: i32,
    #[sea_orm(unique)]
    pub title: String,
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTime,
    pub is_running_meeting: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activity::Entity")]
    Activity,
    #[sea_orm(has_many = "super::course_instructor::Entity")]
    CourseInstructor,
    #[sea_orm(has_many = "super::course_student::Entity")]
    CourseStudent,
}

impl Related<super::activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activity.def()
    }
}

impl Related<super::course_instructor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseInstructor.def()
    }
}

impl Related<super::course_student::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseStudent.def()
    }
}

impl Related<super::student::Entity> for Entity {
    fn to() -> RelationDef {
        super::course_student::Relation::Student.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::course_student::Relation::Course.def().rev())
    }
}

impl Related<super::teacher::Entity> for Entity {
    fn to() -> RelationDef {
        super::course_instructor::Relation::Teacher.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::course_instructor::Relation::Course.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
