//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "course_instructor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub course_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub instructor_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::course::Entity",
        from = "Column::CourseId",
        to = "super::course::Column::CourseId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Course,
    #[sea_orm(
        belongs_to = "super::teacher::Entity",
        from = "Column::InstructorId",
        to = "super::teacher::Column::TeacherId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Teacher,
}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Course.def()
    }
}

impl Related<super::teacher::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teacher.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
