//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::principal::Entity as Principal;
pub use super::student::Entity as Student;
pub use super::teacher::Entity as Teacher;
pub use super::user::Entity as User;
