//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::course::Entity as Course;
pub use super::course_instructor::Entity as CourseInstructor;
pub use super::course_student::Entity as CourseStudent;
pub use super::principal::Entity as Principal;
pub use super::student::Entity as Student;
pub use super::teacher::Entity as Teacher;
pub use super::user::Entity as User;
