//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "teacher")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub teacher_id: i32,
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_instructor::Entity")]
    CourseInstructor,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::course_instructor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseInstructor.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        super::course_instructor::Relation::Course.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::course_instructor::Relation::Teacher.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
